
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

elasticsearch:
  clusterName: elasticsearch
  settings:
    node.name: CarDealership
    
index: cardealership
type: car

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout