
server:
  applicationConnectors:
    - type: http
      port: 14321
  adminConnectors:
    - type: http
      port: 14322

elasticsearch:
  clusterName: elasticsearch
  settings:
    node.name: CarDealership
    
dealershipIndex:
  index: cardealership
  type: car
  numberOfShards: 1
  numberOfReplicas: 0
  

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout